// <auto-generated />
namespace BookRanking.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedcollectioninbooksmodeltryingtoachievemanytomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcollectioninbooksmodeltryingtoachievemanytomany));
        
        string IMigrationMetadata.Id
        {
            get { return "201803161234027_added collection in book's model (trying to achieve many-to-many)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
